user:
  email:
    maximum_length: 255
  name:
    maximum_length: 50
category:
  max_time:
    minimum: 0
question:
  minimum_answers: 4
  correct_answer_number: 1
exams:
  questions_per_exam: 30
  time_limit: 1
  latency: 5
mailer:
  form: "admin@gmail.com"
delay_time: 2
